source "https://supermarket.chef.io"

cookbook 'simple_iptables'
cookbook 'apache2'
cookbook 'mysql'
cookbook 'php'
cookbook 'ntp'
cookbook 'selinux'
cookbook 'sysstat'
cookbook 'openssh'
cookbook 'nodejs'
